name: MLOps Inference Pipeline

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      input_text:
        description: "Inference input text"
        type: string
        default: "premise: A man is playing guitar hypothesis: A person is making music"

jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - list repo root
        run: ls -la

      - name: Build Docker image
        run: docker build -t mlops .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-assignment3-group3:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-assignment3-group3:${{ github.sha }}

      - name: Run inference mode
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          INPUT_TEXT_VALUE="premise: A man is playing guitar hypothesis: A person is making music"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.input_text }}" ]; then
            INPUT_TEXT_VALUE="${{ github.event.inputs.input_text }}"
          fi

          docker run --rm \
            -e APP_MODE=inference \
            -e HF_TOKEN="${HF_TOKEN}" \
            -e INPUT_TEXT="${INPUT_TEXT_VALUE}" \
            mlops
